---

#### 📄 `_config.yml`

```yaml
# Minimal config for GitHub Pages
theme: none
title: DevXTools
description: AI tools for developers, powered by GitHub.

name: Update AI Tools Weekly

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at 00:00
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch trending AI repos (example)
        run: |
          echo "This is a placeholder. Add your automation script here."
          # Use curl + jq + Python/Node to update tools.json
          # Or integrate with Airtable, Make.com, etc.

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tools.json
          git commit -m "🤖 Auto-update: Refresh trending tools" || exit 0
          git push
